CREATE TABLE appointments (
    appointment_id integer GENERATED BY DEFAULT AS IDENTITY,
    token_number smallint NOT NULL,
    user_id integer NOT NULL,
    vendor_id integer NOT NULL,
    service_id integer NOT NULL,
    appointment_date date NOT NULL,
    status text NOT NULL,
    booking_type text NOT NULL,
    notes text,
    created_datetime timestamp with time zone NOT NULL,
    modified_datetime timestamp with time zone,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100),
    CONSTRAINT "PK_appointments" PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appointment_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (vendor_id) ON DELETE CASCADE
);

CREATE TABLE vendor_services (
    service_id integer GENERATED BY DEFAULT AS IDENTITY,
    vendor_id integer NOT NULL,
    service_name character varying(150) NOT NULL,
    service_description text,
    price numeric NOT NULL,
    duration_mins smallint NOT NULL,
    is_active boolean NOT NULL,
    created_datetime timestamp with time zone NOT NULL,
    modified_datetime timestamp with time zone,
    created_by character varying(100) NOT NULL,
    modified_by character varying(100),
    CONSTRAINT "PK_vendor_services" PRIMARY KEY (service_id),
    CONSTRAINT fk_service_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (vendor_id) ON DELETE CASCADE
);

CREATE INDEX "IX_appointments_vendor_id" ON appointments (vendor_id);
CREATE INDEX "IX_vendor_services_vendor_id" ON vendor_services (vendor_id);
